# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test
        run: go test ./...
      - name: Mark releasable
        if: github.ref == 'refs/heads/main'
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state='success' \
            -f description='Mark the commit is able to release binary' \
            -f context='releasable'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
