# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Examples
on:
  push:
  pull_request:

jobs:
  snapcase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Neovim (nightly)
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Save regression snapshots
        run: |
          go run ./cmd/nvim-snap regression save \
            --root snapcase-example \
            --cases-dir snapcase
      - name: Compare regression snapshots
        run: |
          go run ./cmd/nvim-snap regression test \
            --root snapcase-example \
            --cases-dir snapcase \
            --base "${GITHUB_SHA}" \
            --target "${GITHUB_SHA}" \
            --output diff \
            --diff-format text \
            --diff-always
      - name: Run golden tests
        run: |
          go run ./cmd/nvim-snap golden test \
            --root snapcase-example \
            --cases-dir snapcase \
            --output diff \
            --diff-format text \
            --diff-always
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snapcase-example-result
          path: snapcase-example/snapcase/.result/**
