# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release on tag
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: read
    steps:
      - name: Wait commit status
        uses: cloudposse/github-action-wait-commit-status@main
        with:
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          status: releasable
          token: ${{ github.token }}
          check-retry-count: 20
          check-retry-interval: 20
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ~> v2
          args: release --clean
