# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
  workflow_dispatch:
    inputs:
      method:
        description: Which number to increment in the semantic versioning.
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Release Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Actor
        if: github.actor != 'kyoh86'
        run: exit 1
      - name: Check Branch
        if: github.ref != 'refs/heads/main'
        run: exit 1
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump-up Semantic Version
        uses: kyoh86/git-vertag-action@v1
        with:
          method: "${{ github.event.inputs.method }}"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ~> v2
          args: release --clean
